CREATE DATABASE IF NOT EXISTS burgers_db;
USE burgers_db;

CREATE TABLE burgers (
id INTEGER(4) AUTO_INCREMENT NOT NULL PRIMARY KEY,
burger_name VARCHAR(255) NOT NULL,
devoured BOOLEAN NOT NULL DEFAULT FALSE
);

